package com.mygdx.honestmirror.data.persistance.Relations;



import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import androidx.test.core.app.ApplicationProvider;
import androidx.test.ext.junit.runners.AndroidJUnit4;

import com.mygdx.honestmirror.data.persistance.AppDatabase;
import com.mygdx.honestmirror.data.persistance.PersistenceClient;

import static org.junit.Assert.assertTrue;

/**
 * The NNFrameCoordinateDAOTest.
 */
/*
 * Class currently serves only as autogenerated class.
 * If any class specific logic will be made, the logic will be tested here.
 */
@RunWith(AndroidJUnit4.class)
public class NNFrameCoordinateDAOTest {
    private AppDatabase appDatabase;

    /**
     * Create db.
     */
    @Before
    public void createDb() {
        this.appDatabase = PersistenceClient.getInstance(ApplicationProvider.getApplicationContext(), "debugDB").getAppDatabase();
        this.appDatabase.clearAllTables();
    }

    /**
     * Clears all the tables for future unit test cases
     */
    @After
    public void clearDb() {
        this.appDatabase.clearAllTables();
    }

    /**
     * Example test due to lack of testable content.
     */
    @Test
    public void exampleTest() {
        assertTrue(true);
    }

}
