package com.mygdx.honestmirror.data.persistance.Relations;


import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import androidx.test.core.app.ApplicationProvider;
import androidx.test.ext.junit.runners.AndroidJUnit4;

import com.mygdx.honestmirror.data.persistance.AppDatabase;
import com.mygdx.honestmirror.data.persistance.PersistenceClient;

import static org.junit.Assert.assertTrue;


/**
 * The type Nn video frame dao test.
 */
/*
 * Class currently serves only as autogenerated class.
 * If any class specific logic will be made, the logic will be tested here.
 */
@RunWith(AndroidJUnit4.class)
public class NNVideoFrameDAOTest {
    private AppDatabase appDatabase;

    /**
     * Sets up everything required for the unit test.
     */
    @Before
    public void setup() {
        this.appDatabase = PersistenceClient.getInstance(ApplicationProvider.getApplicationContext(), "debugDB").getAppDatabase();
        this.appDatabase.clearAllTables();
    }

    /**
     * Clear db.
     */
    @After
    public void clearDb() {
        this.appDatabase.clearAllTables();
    }

    /**
     * Example test. Due to lack of testable content.
     */
    @Test
    public void exampleTest() {
        assertTrue(true);
    }

}



